### ISSUE TITLE
아이디 찾기 보안 이슈(류한경을 보시요)

### ISSUE THREAD

**Issue by Lee-JongSoo** [VolunteerPlatform/backend#2]
아이디 찾기 할 때 임의의 유저가 나의 회원가입한 정보 중에 이름하고 휴대폰 번호 있으면 무한으로 계속 내 핸드폰 한테 아이디를 보낼 수 있는데 이를 어떻게 막을 지??

방법 1 : 아이디 찾기를 하루에 몇번 이하 제한을 둔다
방법 2 : ?
아이디어 제시좀요

**Comment by han-gyeong** [comment]
하루에 5번 제한을 두면 좋을 것 같습니다!

**Comment by Lee-JongSoo** [comment]
ㅇㅋㅇㅋ 그건 천천히 개발하도록 할게
